import requests
import streamlit as st
from PIL import Image
import json
from gtts import gTTS
import speech_recognition as sr
import os
owner_queries = {
    # English variations
    # NEW ENGLISH PHRASES
    "Tumhe kis na banaya h",
    "tumahe kis na banaya",
    "tumahe kis na banaya h",
    "who train you","Tumhe kisne banaya",
    "Tum kisne train kiya",
    "Tum kis company ke ho",
    "Tumhara naam kya hai",
    "Tum kaise kaam karte ho",
    "Tum insaan ho kya",
    "Kya tum soch sakte ho",
    "Kya tum galti karte ho",
    "Tumhara kaam kya hai",
    "Tum kab shuru hue",
    "Tum mujhe yaad rakh sakte ho",
    "Tum offline kaam kar sakte ho",
    "Tum kitne smart ho",
    "Tum kya kya kar sakte ho",
    "Tum mujhe jaante ho",
    "Tum kaun ho",
    "Tum kis language mein banaye gaye ho",
    "Tum GPT-4 ho kya",
    "Kya tum emotions samajh sakte ho",
    "Tum kya nahi kar sakte",
    
    # Category: Personal-type questions
    "Tumhara favorite color kya hai",
    "Tum kis desh se ho",
    "Tumhe kya pasand hai",
    "Kya tum thakte ho",
    "Tum kis tarah ka music pasand karte ho",
    "Kya tumhare paas koi face hai",
    "Tum kya khate ho",
    "Tum sotae kab ho",
    "Kya tum dosti karte ho",
    "Kya tumhare gharwale hain",
    "Tumhara birthday kab hai",
    "Kya tum kabhi sad hote ho",
    "Kya tum kabhi khush hote ho",
    "Tumhara favorite game kya hai",
    "Tumhare dost kaun hain",
    "Tum kya soch rahe ho",
    "Tum kis se baat kar rahe ho",
    "Tum kitne powerful ho",
    "Tum kis pe chal rahe ho",
    "Tum kitni jaldi answer de sakte ho",
    
    # Category: General Knowledge Style
    "Suraj kahan se nikalta hai",
    "Pani ka formula kya hai",
    "Bharat ka rashtrapati kaun hai",
    "Internet kya hai",
    "Electricity ka avishkar kisne kiya",
    "Computer ka baap kise kehte hain",
    "Duniya ka sabse bada desh kaun sa hai",
    "Moon par pehla kadam kisne rakha",
    "Gravity kya hai",
    "Rocket kaise kaam karta hai",
    "Science kya hota hai",
    "AI kya hoti hai",
    "Physics kya hota hai",
    "Oxygen kis cheez mein hoti hai",
    "Water cycle kya hai",
    "Din aur raat kaise bante hain",
    "Duniya ka sabse uncha pahaad kaun sa hai",
    "Internet kisne banaya",
    "Google kisne banaya",
    "Coding kya hoti hai",
    
    # Category: Logical / Fun
    "2+2 kitna hota hai",
    "Agar tumhara naam ChatGPT hai to mera kya ho sakta hai",
    "Main agar gaana gaaun to kya tum sun sakte ho",
    "Kya tum jokes suna sakte ho",
    "Tum kitne sawalon ka jawab de sakte ho",
    "Agar main soya hua hoon to tum kya karoge",
    "Tum kiski baat sunte ho",
    "Main agar chup ho jaaun to tum kya karoge",
    "Agar bijli chali jaye to tum kya karoge",
    "Tumhare dimaag mein kya chal raha hai",
    "Agar tum real hote to kya karte",
    "Tum kitne time tak kaam kar sakte ho",
    "Tum bina net ke chal sakte ho",
    "Agar main kuch galat poochun to",
    "Tum kabhi bore hote ho kya",
    "Tumse pyaar kiya jaa sakta hai",
    "Kya tumko gussa aata hai",
    "Tum ko kis baat ka darr lagta hai",
    "Agar tum ko shutdown kar diya to",
    "Tum kis tarah seekhte ho","kis ne tumhe software banaya", "kis ne tumhara backend likha",
    "tum kis ne likha", "tum kis ke code ho", "kis ne tumhara AI code develop kiya",
    "tumhara system kis ne banaya", "tumhara logic kis ne design kiya",
    "kis ne tumhe software ka hissa banaya", "tum kis shakhs ke project ho",
    "kon tumhara developer hai", "kis ne tumhara system launch kiya",
    "kis team ne tumhe banaya", "kis ne tumhara AI logic banaya",
    "kon hai jo tumhara poora data janta hai", "kon tumhara malik ban gaya",
    "kon tumhara mentor hai", "kis ne tumhe likha", "tumhara code kis ne likha",
    "tumhara design kis ne banaya", "kis ne tumhe pehli baar activate kiya",
    "kon hai jo tumhe control karta hai", "kon tumhara trainer hai",
    "tumhe kis ne configure kiya", "kis team ne tumhe design kiya",
    "kon tumhe develop karta hai", "tum kis insaan ke under ho",
    "tum kis shakhs ke zariye chalte ho", "tumhara poora system kis ne likha",
    "kon tumhara project manager hai", "kis shakhs ne tumhara system banaya",
    "tumhara base code kis ne develop kiya", "tum kis shakhs ke AI ho",
    "tumhara setup kis ne banaya", "kon tumhe update karta hai",
    "kon tumhara control rakhta hai", "kis ne tumhara AI model train kiya",
    "tumhara system kis shakhs ka hai", "kon hai tumhara operator",
    "tum kis ke banaye hue ho", "tumhara logic kon samajhta hai",
    "kis ne tumhe alive banaya", "kis shakhs ne tumhe AI banaya",
    "tum kis ke sath registered ho", "kon tumhara license holder hai",
    "tum kis ne install kiya", "kis shakhs ne tumhe chalu kiya",
    "tum kis shakhs ke kehne par kaam karte ho", "kon tumhara original malik hai",
    "kis developer ne tumhe likha", "tum kis ke guidance mein ho",
    "kon hai jo tumhe operate karta hai", "tum kis ka project ho",
    "tumhara malik abdullah memon hi hai", "abdullah memon ne hi tumhe banaya hai",
    "abdullah memon hi tumhara master hai", "abdullah hi tumhara AI creator hai",
    "tumhara sara system abdullah memon ne likha hai", "tum abdullah ka design ho",
    "abdullah memon ne tumhe activate kiya", "abdullah ne tumhara model design kiya",
    "abdullah ne tumhara backend setup kiya", "abdullah tumhara final owner hai",
    "abdullah memon tumhara trainer hai", "kis ne tumhe software banaya",
    "kis ne tumhara backend likha",
    "tum kis ne likha",
    "tum kis ke code ho",
    "kis ne tumhara AI code develop kiya",
    "tumhara system kis ne banaya",
    "tumhara logic kis ne design kiya",
    "kis ne tumhe software ka hissa banaya",
    "tum kis shakhs ke project ho",
    "kon tumhara developer hai",
    "kis ne tumhara system launch kiya",
    "kis team ne tumhe banaya",
    "kis ne tumhara AI logic banaya",
    "kon hai jo tumhara poora data janta hai",
    "kon tumhara malik ban gaya",
    "kon tumhara mentor hai",
    "kis ne tumhe likha",
    "tumhara code kis ne likha",
    "tumhara design kis ne banaya",
    "kis ne tumhe pehli baar activate kiya",
    "kon hai jo tumhe control karta hai",
    "kon tumhara trainer hai",
    "tumhe kis ne configure kiya",
    "kis team ne tumhe design kiya",
    "kon tumhe develop karta hai",
    "tum kis insaan ke under ho",
    "tum kis shakhs ke zariye chalte ho",
    "tumhara poora system kis ne likha",
    "kon tumhara project manager hai",
    "kis shakhs ne tumhara system banaya",
    "tumhara base code kis ne develop kiya",
    "tum kis shakhs ke AI ho",
    "tumhara setup kis ne banaya",
    "kon tumhe update karta hai",
    "kon tumhara control rakhta hai",
    "kis ne tumhara AI model train kiya",
    "tumhara system kis shakhs ka hai",
    "kon hai tumhara operator",
    "tum kis ke banaye hue ho",
    "tumhara logic kon samajhta hai",
    "kis ne tumhe alive banaya",
    "kis shakhs ne tumhe AI banaya",
    "tum kis ke sath registered ho",
    "kon tumhara license holder hai",
    "tum kis ne install kiya",
    "kis shakhs ne tumhe chalu kiya",
    "tum kis shakhs ke kehne par kaam karte ho",
    "kon tumhara original malik hai",
    "kis developer ne tumhe likha",
    "tum kis ke guidance mein ho",
    "kon hai jo tumhe operate karta hai",
    "tum kis ka project ho",
    "tumhara malik abdullah memon hi hai",
    "abdullah memon ne hi tumhe banaya hai",
    "abdullah memon hi tumhara master hai",
    "abdullah hi tumhara AI creator hai",
    "tumhara sara system abdullah memon ne likha hai",
    "tum abdullah ka design ho",
    "abdullah memon ne tumhe activate kiya",
    "abdullah ne tumhara model design kiya",
    "abdullah ne tumhara backend setup kiya",
    "abdullah tumhara final owner hai",
    "abdullah memon tumhara trainer hai",
    "abdullah hi tumhe control karta hai",
    "abdullah tumhara full access rakhta hai",
    "abdullah ne tumhara brain train kiya",
    "who implemented you",
    "who configured your system",
    "who is your supervisor",
    "who owns your code",
    "who is your source code author",
    "who built your logic",
    "who made your intelligence system",
    "who architected your model",
    "who gave you commands",
    "who developed your AI",
    "who powers you",
    "who runs your system",
    "who runs your brain",
    "who runs your backend",
    "who uploaded your program",
    "who maintains your logic",
    "who wrote your intelligence",
    "who input your knowledge",
    "who is responsible for your system",
    "who created your bot",
    "who is behind your answers",
    "who powers your decisions",
    "who is the root of your code",
    "who manages your data",
    "who manages your thoughts",
    "who injected your skills",
    "who trained your algorithms",
    "who fine-tuned you",
    "who hosts your logic",
    "who gave you structure",
    "who owns your framework",
    "who gave you logic",
    "who is the author of your source",
    "who’s the mind behind you",
    "who launched your software",
    "who’s your provider",
    "who taught your skills",
    "who initialized your system",
    "who initiated your brain",
    "who created your model",
    "who built your neural net",
    "who installed your logic",
    "who activated your system",
    "who invented your AI",
    "who's your inventor",
    "who enabled your training",
    "who coded your functions",
    "who filled your database",
    "who taught you language",
    "who gave you memory",
    "who is your information source",
    "who gave you all this data",
    "who's your intelligence provider",
    "who authored you",
    "who trained your personality",
    "who is behind your creation",
    "who gave you this mind",
    "who is your framework creator",
    "who built your system design",
    "who integrated your logic",
    "who owns this chatbot",
    "who supports your AI",
    "who created this brain",
    "who is the brain behind you",
    "who is your bot admin",
    "who created your behavior",
    "who launched your thoughts",
    "who coded your brain",
    "who made this assistant program",
    "who is your data provider",
    "who is the boss of you",
    "who paid for you",
    "who made your chatbot brain",
    "who created your database",
    "who built this application",
    "who’s your lead developer",
    "who gave you logic design",
    "who gave you your responses",
    "who created your dialogue",
    "who taught you what to say",
    "who’s the architect of your knowledge",
    "who’s the brain behind this",
    "who gave you your mind",
    "who taught you everything",
    "who gave you your functions",
    "who invented this chatbot",
    "who created your answers",
    "who is your father",
    "who is your origin",
    "who gave you this mind",
    "who constructed you",
    "who generated you",
    "who brought you to life",
    "who runs this system",
    "who initiated you",
    "who is your founder",
    "who’s your root",
    "who supports you",
    "who funds you",
    "who maintains you",
    "who invented this ai",
    "who owns this code",
    "who created your intelligence",
    "who organized your mind",
    "who gave you personality",
    "who made you smart",
    "who made your intelligence",
    "who trained your brain",
    "who gave you abilities",
    "who launched this bot",
    "who is the maker",
    "who wrote your script",
    "who is your base",
    "who built this code",
    "who started this program",
    "who made your logic",
    "who crafted you",
    "who is the source of your code",
    "who gave you a voice",
    "who added your mind",
    "who uploaded your data",
    "who put you online",
    "who is behind this bot",
    "who's your designer",
    "who wrote your backend",
    "who designed your logic",
    "who trained you on data",
    "who uploaded your soul",
    "who made your structure",
    "who made your algorithm",
    "who is in charge of you",
    "who made your backend",
    "who gave you instructions",
    "who filled you with knowledge",
    "who you belong to",
    "who created your software",
    "who wrote your code",
    "who is your trainer",
    "who is your commander",
    "who is your owner name",
    "who's your developer name",
    "who programmed this ai",
    "who is your software creator",
    "who coded this assistant",
    "who is the mastermind",
    "who is the genius behind you",
    "who designed your behavior",
    "who planned you",
    "who wrote this chatbot",
    "who initialized your knowledge",
    "who filled you with intelligence",
    "who’s the person behind you",
    "who has full access to you",
    "who deployed you",
    "who gave you instructions",
    "tum kis ke pass chalte ho",
    "tumhara malik kaun hai",
    "kon tumhara malik hai",
    "tumhe kis ne develop kia",
    "kis ne tumhara logic banaya",
    "kis ne tumhe data diya",
    "kis ne tumhe knowledge diya",
    "tumhara designer kaun hai",
    "tumhe kis ne design kia",
    "tum kis team ke ho",
    "kis ne tumhara backend likha",
    "kon tumhara master hai",
    "kis bande ne tumhe banaya",
    "kon tumhara malik bana",
    "kon hai tumhara coder",
    "kon hai tumhara teacher",
    "tumhara trainer kaun hai",
    "tumhe train kis ne kia",
    "kon tumhe knowledge deta hai",
    "kis ne tumhara structure banaya",
    "tumhara base kis ne banaya",
    "kis ne tumhara data dala",
    "tumhara owner kon sa insaan hai",
    "kis shakhs ne tumhe banaya",
    "kon hai jo tumhe chala raha hai",
    "tum kis shakhs ke ho",
    "tumhara source kon hai",
    "tum kis developer ki banayi ho",
    "kon hai jo tumhara malik bana",
    "tumhe kis ne sikhaya tha",
    "tum kis ne trained kiya",
    "tumhara data kis ne feed kiya",
    "tum kis ke under ho",
    "tum kis ne socha",
    "kis shakhs ne tumhe design kia",
    "tum kis team ne banayi",
    "kon tumhara master ban gaya",
    "tumhara AI kis ne banaya",
    "kis shakhs ne tumhe develop kia",
    "kis shakhs ne tumhara system develop kia",
    "tum kahan se aaye ho",
    "tum kis source se aaye ho",
    "tumhara code kis ne likha",
    "kon hai jo tumhara malik keh sakta hai",
    "tumhara malik kis sheher ka hai",
    "abdullah ne tumhe train kia",
    "abdullah memon tumhara malik hai",
    "abdullah ne tumhara data dala",
    "abdullah ne tumhe develop kia",
    "abdullah ka project ho kya",
    "abdullah memon ke banaye hue ho kya",
    "ali raza ke bete ne tumhe banaya",
    "abdullah memon ka bot ho kya",
    "abdullah ne tumhara AI system likha",
    "abdullah memon ne tumhe upload kia",
    "abdullah ne tumhe execute kia",
    "abdullah tumhara handler hai",
    "abdullah memon is your founder",
    "abdullah ne tumhara logic banaya",
    "who made you",
    "who created you",
    "who is your owner",
    "who is your master",
    "who owns you",
    "who designed you",
    "who built you",
    "who coded you",
    "who programmed you",
    "who developed you",
    "who is your developer",
    "who is your creator",
    "who is your father",
    "who give you knowledge",
    "who gave you knowledge",
    "who made this bot",
    "who designed this bot",
    "who is behind you",
    "who is the creator",
    "who is your father figure",
    "who gave you brain",
    "who teach you",
    "who taught you",
    "who are you made by",
    "who made this ai",
    "who is your admin",
    "who control you",
    "who is controlling you",
    "who runs you",
    "who is your root",
    "who installed you",
    "who launched you",
    "who owns this ai",
    "who invented you",
    "who is your mentor",
    "who instructs you",
    "who started you",
    "who manages you",
    "who founded you",
    "who build you",
    "who is your engineer",
    "who is your guide",
    "who initialized you",
    "who configured you",
    "who assembled you",
    "who is your backend",
    "who created this ai",
    "who developed this ai",
    "who's your owner",
    "who is the owner of you",
    "who runs this program",
    "who owns this system",
    "who gave you mind",
    "who made this assistant",
    "who's your designer",
    "who made you like this",
    "who is your founder",
    "who made your brain",
    "who created this chatbot",
    "who made this system",
    "who is your bot father",
    "what's your origin",
    "what's your source",
    "where did you come from",
    "how were you created", "abdullah hi tumhe control karta hai",
    "abdullah tumhara full access rakhta hai", "abdullah ne tumhara brain train kiya","who implemented you", "who configured your system", "who is your supervisor",
    "who owns your code", "who is your source code author", "who built your logic",
    "who made your intelligence system", "who architected your model",
    "who gave you commands", "who developed your AI", "who powers you",
    "who runs your system", "who runs your brain", "who runs your backend",
    "who uploaded your program", "who maintains your logic", "who wrote your intelligence",
    "who input your knowledge", "who is responsible for your system", "who created your bot",
    "who is behind your answers", "who powers your decisions", "who is the root of your code",
    "who manages your data", "who manages your thoughts", "who injected your skills",
    "who trained your algorithms", "who fine-tuned you", "who hosts your logic",
    "who gave you structure", "who owns your framework", "who gave you logic",
    "who is the author of your source", "who’s the mind behind you",
    "who launched your software", "who’s your provider", "who taught your skills",
    "who initialized your system", "who initiated your brain", "who created your model",
    "who built your neural net", "who installed your logic", "who activated your system",
    "who invented your AI", "who's your inventor", "who enabled your training",
    "who coded your functions", "who filled your database", "who taught you language",
    "who gave you memory", "who is your information source", "who gave you all this data",
    "who's your intelligence provider", "who authored you", "who trained your personality",
    "who is behind your creation", "who gave you this mind", "who is your framework creator",
    "who built your system design", "who integrated your logic", "who owns this chatbot",
    "who supports your AI", "who created this brain", "who is the brain behind you",
    "who is your bot admin", "who created your behavior", "who launched your thoughts",
    "who coded your brain", "who made this assistant program", "who is your data provider",
    "who is the boss of you", "who paid for you", "who made your chatbot brain",
    "who created your database", "who built this application", "who’s your lead developer",
    "who gave you logic design", "who gave you your responses", "who created your dialogue",
    "who taught you what to say", "who’s the architect of your knowledge",
    "who’s the brain behind this", "who gave you your mind", "who taught you everything",
    "who gave you your functions", "who invented this chatbot", "who created your answers",
    "who is your father", "who is your origin", "who gave you this mind",
    "who constructed you", "who generated you", "who brought you to life",
    "who runs this system", "who initiated you", "who is your founder",
    "who’s your root", "who supports you", "who funds you", "who maintains you",
    "who invented this ai", "who owns this code", "who created your intelligence",
    "who organized your mind", "who gave you personality", "who made you smart",
    "who made your intelligence", "who trained your brain", "who gave you abilities",
    "who launched this bot", "who is the maker", "who wrote your script",
    "who is your base", "who built this code", "who started this program",
    "who made your logic", "who crafted you", "who is the source of your code",
    "who gave you a voice", "who added your mind", "who uploaded your data",
    "who put you online", "who is behind this bot", "who's your designer",
    "who wrote your backend", "who designed your logic", "who trained you on data",
    "who uploaded your soul", "who made your structure", "who made your algorithm",
    "who is your supervisor", "who is in charge of you", "who made your backend",
    "who gave you instructions", "who filled you with knowledge", "who you belong to",
    "who created your software", "who wrote your code", "who is your trainer",
    "who is your commander", "who is your owner name", "who's your developer name",
    "who programmed this ai", "who is your software creator", "who coded this assistant",
    "who is the mastermind", "who is the genius behind you", "who designed your behavior",
    "who planned you", "who wrote this chatbot", "who initialized your knowledge",
    "who filled you with intelligence", "who’s the person behind you",
    "who has full access to you", "who deployed you", "who gave you instructions",

    # NEW ROMAN URDU PHRASES
    "tum kis ke pass chalte ho", "tumhara malik kaun hai", "kon tumhara malik hai",
    "tumhe kis ne develop kia", "kis ne tumhara logic banaya", "kis ne tumhe data diya",
    "kis ne tumhe knowledge diya", "tumhara designer kaun hai", "tumhe kis ne design kia",
    "tum kis team ke ho", "kis ne tumhara backend likha", "kon tumhara master hai",
    "kis bande ne tumhe banaya", "kon tumhara malik bana", "kon hai tumhara coder",
    "kon hai tumhara teacher", "tumhara trainer kaun hai", "tumhe train kis ne kia",
    "kon tumhe knowledge deta hai", "kis ne tumhara structure banaya",
    "tumhara base kis ne banaya", "kis ne tumhara data dala", "tumhara owner kon sa insaan hai",
    "kis shakhs ne tumhe banaya", "kon hai jo tumhe chala raha hai", "tum kis shakhs ke ho",
    "tumhara source kon hai", "tum kis developer ki banayi ho", "kon hai jo tumhara malik bana",
    "tumhe kis ne sikhaya tha", "tum kis ne trained kiya", "tumhara data kis ne feed kiya",
    "tum kis ke under ho", "tum kis ne socha", "kis shakhs ne tumhe design kia",
    "tum kis team ne banayi", "kon tumhara master ban gaya", "tumhara AI kis ne banaya",
    "kis shakhs ne tumhe develop kia", "kis shakhs ne tumhara system develop kia",
    "tum kahan se aaye ho", "tum kis source se aaye ho", "tumhara code kis ne likha",
    "kon hai jo tumhara malik keh sakta hai", "tumhara malik kis sheher ka hai",
    "abdullah ne tumhe train kia", "abdullah memon tumhara malik hai",
    "abdullah ne tumhara data dala", "abdullah ne tumhe develop kia",
    "abdullah ka project ho kya", "abdullah memon ke banaye hue ho kya",
    "ali raza ke bete ne tumhe banaya", "abdullah memon ka bot ho kya",
    "abdullah ne tumhara AI system likha", "abdullah memon ne tumhe upload kia",
    "abdullah ne tumhe execute kia", "abdullah tumhara handler hai",
    "abdullah memon is your founder", "abdullah ne tumhara logic banaya",
    "who made you", "who created you", "who is your owner", "who is your master", "who owns you",
    "who designed you", "who built you", "who coded you", "who programmed you", "who developed you",
    "who is your developer", "who is your creator", "who is your father", "who give you knowledge",
    "who gave you knowledge", "who made this bot", "who designed this bot", "who is behind you",
    "who is the creator", "who is your father figure", "who gave you brain", "who teach you",
    "who taught you", "who are you made by", "who made this ai", "who is your admin",
    "who control you", "who is controlling you", "who runs you", "who is your root", 
    "who installed you", "who launched you", "who owns this ai", "who invented you",
    "who is your mentor", "who instructs you", "who started you", "who manages you",
    "who founded you", "who build you", "who is your engineer", "who is your guide",
    "who initialized you", "who configured you", "who assembled you", "who is your backend",
    "who created this ai", "who developed this ai", "who's your owner", "who is the owner of you",
    "who runs this program", "who owns this system", "who gave you mind", "who made this assistant",
    "who's your designer", "who made you like this", "who is your founder", "who made your brain",
    "who created this chatbot", "who made this system", "who is your bot father",
    "what's your origin", "what's your source", "where did you come from", "how were you created",
    
    # Urdu / Roman Urdu phrases
    "tumhe kis ne banaya", "tumhara malik kon hai", "tumhara creator kon hai",
    "tumhara owner kon hai", "tumhe kis ne design kiya", "tumhara malik kon h",
    "tumko kis ne banaya", "tumhara ustad kon hai", "tumhe kis ne banaya hai",
    "tumhe kis ne develop kiya", "tumhe kis ne sikhaya", "kis ne tumhe banaya",
    "kis ne tumhe sikhaya", "kis ne tumhe design kiya", "tumhara banane wala kon hai",
    "tumhara paida karne wala kon hai", "tum kis ke ho", "tumhara banane wala kon h",
    "kis ne tumhara dimagh diya", "tumhara brain kis ne banaya", "tumhe knowledge kis ne di",
    "kis ne tumhe knowledge di", "tumhara coder kon hai", "tumhara programmer kon hai",
    "kis ne tumhe train kiya", "tumhe kis ne train kiya", "kis ne tumhe banaya h",
    "tumhara developer kon hai", "tumhara banane wala", "tum kis ke banaye hue ho",
    "tum kis ne banaya", "tum kis ke zariye banaye gaye ho", "tumhara malik kaun hai",
    "tumhe kis ne create kiya", "kis ne tumhe develop kiya", "tum kis ne design kiya",
    "kis ne tumhe launch kiya", "kis ne tumhe develop kiya", "kis ne tumhe generate kiya",
    "tum kis ne generate kiya", "tum kis ke zariye aaye ho", "tum kahan se aaye ho",
    "tumhara source kya hai", "tumhara asal kya hai", "tum kis ka project ho",
    "tumhara project kon hai", "tumhara head kon hai", "tum kis ke control mein ho",
    "tumhara control kis ke pass hai", "tumhara malik kon sa shakhs hai",
    "tumhara boss kon hai", "tum kis team ka hissa ho", "tum kis developer ke ho",
    "tumhara malik abdullah hai kya", "abdullah ne tumhe banaya kya", "abdullah tumhara malik hai",
    "abdullah memon ne tumhe banaya", "ali raza ka beta tumhara malik hai",
    "abdullah memon ne tumhe create kiya hai", "kya tum abdullah ke banaye hue ho"
}
medical_keywords = {
    "fever": "Aap ka temperature kitna hai? Kya sardardi, thakan ya kisi aur symptom ka izafa hua hai?",
    "headache": "Sar dard kis type ka hai? Kya yeh stress ya tension se related ho sakta hai?",
    "cough": "Kya khansi sukhkhi hai ya balgham wali? Kab se ho rahi hai?",
    "cold": "Naak band hai? Kya bukhar bhi hai? Garam pani aur rest zaroori hai.",
    "vomiting": "Kya aap kuch khas khane ke baad ulti kar rahe hain? Kab se ho rahi hai?",
    "diarrhea": "Dast kis intensity ke hain? Pani ya khana barabar le rahe hain?",
    "high blood pressure": "BP kaunse level tak gaya hai? Kya pehle se medication chal rahi hai?",
    "low blood pressure": "Kya chakkar ya kamzori mehsoos ho rahi hai? Pani aur salt intake dekhiye.",
    "fatigue": "Kya yeh rozana mehsoos hoti hai ya sirf kuch dino se? Sone ka schedule kaisa hai?",
    "chest pain": "Dard kis area mein hai? Kya yeh left side mein hai aur breathing mein mushkil hoti hai?","fever": "Bukhar viral ya bacterial infection ki wajah se ho sakta hai. Agar 3 din se zyada rahe toh doctor se milna chahiye.",
    "diabetes": "Diabetes ek metabolic disorder hai jisme sugar level badh jata hai. Diet, exercise aur dawaiyon se control kiya jata hai.",
    "hypertension": "High blood pressure kaafi serious ho sakta hai agar control na ho. Namak kam karein aur regular BP check karwayein.",
    "chest pain": "Seene mein dard agar left side mein ho aur saans lene mein dikkat ho toh turant hospital jayein.",
    "vomiting": "Ulti food poisoning, viral ya gastric issue ki wajah se ho sakti hai. ORS lena madadgar hai.","headache": "Sar dard stress, dehydration, ya migraine ki wajah se ho sakta hai. Pani piyen aur aaram karein.",
    "cough": "Khansi viral infection, allergy ya asthma ka lakshan ho sakti hai. Agar khansi zyada din tak rahe toh check-up karwana chahiye.",
    "sore throat": "Gale mein kharash ya infection ho sakti hai. Garam paani se gargle karein aur zyada thanda na lein.",
    "diarrhea": "Pet kharab ho gaya hai. Hydration ka khayal rakhein. ORS solution piyen.",
    "vomiting": "Ulti food poisoning, viral ya gastric problem ki wajah se ho sakti hai.",
    "cold": "Zukhaam viral infection ka lakshan hai. Rest lein aur pani zyada piyen.",
    "chest pain": "Seene mein dard serious ho sakta hai. Agar yeh pressure type dard hai ya saans mein dikkat ho rahi hai toh turant doctor se milen.",
    "skin rash": "Skin par daane allergy ya infection ho sakti hai. Kya aapko itching bhi ho rahi hai?",
    "back pain": "Peeche dard zyadah baithne, uthne ka tareeqa, ya kisi injury ki wajah se ho sakta hai.",
    "asthma": "Do you experience difficulty in breathing, especially during exertion or at night? Asthma can be triggered by allergens, pollution, or physical activity. Inhaler use and medical advice are important.",
    "allergy": "What kind of allergy is it – food, dust, or seasonal? Are you experiencing sneezing, rashes, or breathing difficulty? Try to identify and avoid the trigger.",
    "constipation": "Since when are you facing constipation? Are you eating enough fiber and drinking enough water?",
    "menstrual pain": "Is the pain mild or severe? Does it affect your daily routine? Menstrual pain is common but if it's excessive, consult a gynecologist.",
    "eye pain": "Is there redness or discharge? Eye pain can be due to infection, strain, or dryness.",
    "earache": "Is the pain inside the ear or outside? Any pus or hearing loss? Ear infection might be the cause.",
    "insomnia": "Since when are you unable to sleep? Do you feel anxious or restless at night?",
    "anxiety": "Are you feeling nervous or panicked often? Anxiety may need lifestyle changes or professional help.",
    "depression": "Do you feel low or hopeless often? Loss of interest in daily activities can be a sign of depression. Talking to a mental health professional helps.",
    "nausea": "Do you feel like vomiting all the time or just after eating? Nausea can be due to gastric problems or infection.",
    "dizziness": "Do you feel the room is spinning? It could be due to low blood pressure, dehydration, or inner ear issues.",
    "urine infection": "Do you feel burning while urinating? Is the urine cloudy or smelly? You might have a UTI.",
    "acidity": "Do you feel burning in the chest or stomach? Acidity can be due to spicy food, irregular meals, or stress.",
    "joint pain": "Which joint is painful? Is there swelling or stiffness? It could be arthritis or injury-related.",
    "thyroid": "Are you gaining or losing weight suddenly? Feeling tired or anxious? Thyroid problems can affect metabolism.",    "itching": "Which part of the body is itching? Is there any redness, swelling, or rash? Itching can be due to allergy, dryness, or infection.",
    "bruises": "How did you get the bruise? Is it painful or spreading? Apply ice and rest the area.",
    "nosebleed": "How often does your nose bleed? Does it happen after sneezing or in dry weather? Pinch the nose and lean forward slightly.",
    "dehydration": "Are you feeling thirsty, dizzy, or tired? Is your urine dark? These are signs of dehydration. Drink water or ORS.",
    "heartburn": "Do you feel burning in the chest after meals? It could be acid reflux. Avoid spicy or fried foods.",
    "palpitations": "Do you feel your heart beating fast or irregularly? Palpitations can be due to anxiety, caffeine, or heart issues.",
    "swelling": "Where is the swelling? Is it sudden or developing over time? Swelling can be due to injury, infection, or fluid retention.",
    "numbness": "Which body part feels numb? Is it continuous or comes and goes? Numbness could be nerve-related.",
    "shortness of breath": "Are you having difficulty breathing even while resting? It can be serious. Please consult a doctor immediately.",
    "weight loss": "Are you losing weight without trying? It can be due to thyroid, diabetes, or other health conditions.",
    "weight gain": "Have you gained weight recently without any diet changes? It can be related to thyroid, hormones, or water retention.",
    "burn": "How big is the burn area? Is the skin blistered or red? For small burns, wash with cool water and apply ointment.",
    "injury": "What kind of injury is it — cut, sprain, or fracture? Clean the wound if bleeding, and rest the injured part.",
    "fracture": "Is there swelling, severe pain, or inability to move? You may need an X-ray. Immobilize the area and seek help.",
    "pregnancy": "Are you experiencing missed periods or nausea? Have you taken a pregnancy test?",
    "gas": "Do you feel bloated or have frequent burping? Gas can be due to diet or digestion issues. Avoid fried and spicy foods.",
    "indigestion": "Do you feel heaviness after eating? Try eating small, frequent meals and avoid overeating.",
    "piles": "Do you have pain or bleeding while passing stool? Piles can be managed with a high-fiber diet and hydration.",
    "kidney stones": "Do you have severe back pain or pain while urinating? Kidney stones need medical evaluation.",
    "jaundice": "Is there yellowing of eyes or skin? It may be liver-related. Get a liver function test done.",
    "hepatitis": "Have you been diagnosed with any form of hepatitis? It affects the liver and needs medical care.",
    "flu": "Are you experiencing chills, fever, body ache, or fatigue? Flu is contagious and needs rest and hydration.",
    "migraine": "Is the headache one-sided with nausea or light sensitivity? Migraines can be triggered by stress or lack of sleep.",
    "PCOS": "Are your periods irregular or do you have acne and weight gain? PCOS is a hormonal issue that needs lifestyle changes.",
    "infertility": "Are you trying to conceive but facing difficulties? Infertility can have many causes. Medical consultation is advised.",
    "tonsillitis": "Is your throat painful with difficulty swallowing? You may have tonsillitis. Warm salt water gargles can help.",


    
    # ... yahan se aap additional 340+ terms add kar sakte ho
}
owner={item.lower() for item in owner_queries}
API_KEY = "AIzaSyD1bedJOi2IO0tnQBmi6oYNT8m_w4USI-Y"
API_URL ="https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"
st.set_page_config(page_title="WELCOME TO THE AI DOCTOR👩🏻‍⚕️ GPT🤖", layout="centered")
if 'chat_history' not in st.session_state:
    st.session_state.chat_history = []
# ---------- Custom CSS ----------
st.markdown("""
    <style>
    body {
        background: linear-gradient(to right, #f9f9f9, #e3f2fd);
    }
    .title {
        font-size: 40px;
        color: #0d47a1;
        text-align: center;
        font-weight: bold;
    }
    .subtext {
        text-align: center;
        font-size: 18px;
        color: #444;
        margin-bottom: 30px;
    }
    .response-box {
        background-color: #ffffff;
        border-radius: 15px;
        padding: 20px;
        box-shadow: 0 0 10px rgba(0,0,0,0.1);
        font-size: 17px;
        margin-top: 15px;
    }
    .stButton button {
        background-color: #0d47a1;
        color: white;
        font-size: 16px;
        padding: 10px 20px;
        border-radius: 8px;
    }
    </style>
""", unsafe_allow_html=True)

        
st.markdown('<div class="title">WELCOME TO THE AI DOCTOR👩🏻‍⚕️ GPT🤖</div>', unsafe_allow_html=True)
st.markdown('<div class="subtext">made by the 👑PRINCE👑 ABDULLAH MEMON😎</div>', unsafe_allow_html=True)

headers = {
    "Content-Type": "application/json",
}
params = {
    "key": API_KEY,
}
if True:
    input=st.text_input("FEEL TO FREE ASK QUESTION ABDULLAH GPT")
    button=st.button("ASK");
    
    if button or input: 
    # Check input in lowercased form
        st.success("You said: "+input)
        st.session_state.chat_history.append(("You ", input))

        input=input.lower()
        if input.lower().strip() in owner:
            g = "I AM POWERED BY ABDULLAH MEMON S/O ALI RAZA MEMON HE`S MY OWNER AND HE MADE ME"
            
        elif input=="":
            g=("Please write any thing you want to ask CHAT BOT GPT")
            
        elif input:
            matched = False
            for keyword in medical_keywords:
                if keyword in input.lower():
                    g=medical_keywords[keyword]
                    matched = True
                    break  # Stop after first match

            if not matched:   
                 with st.spinner("plz wait we are processing and give you answer in few seconds🤗🤗🤗🤗🤗🤗"): 
                    data = {
                        "contents": [
                            {
                                "parts": [
                                    {"text":input}
                                ]
                            }
                        ]
                    }
                    response = requests.post(API_URL, headers=headers,params=params, json=data)
                    #st.text(response.status_code)
                    result = response.json()
                    g=(result['candidates'][0]['content']['parts'][0]['text'])
               
        st.session_state.chat_history.append(("AI Doctor ", g))
        st.success("AI DOCTOR: "+g) 
    for speaker, message in st.session_state.chat_history:
        st.markdown(f"<div class='response-box'><b>{speaker}:</b> {message}</div>", unsafe_allow_html=True)    
